Check max allowed SemVer bump
paritytech/parity-publish pull request #31
Opened 2024-06-17 15:18 UTC by ggwpez

Adds a `--max-allowed-bump` to the `prdoc` subcommand to restrict the maximal allowed bump kind.  
This can then be used for the backport CI, where we only allow up to `minor` changes.

2024-06-20 11:24 UTC, muharem approved these changes

2024-06-25 12:30 UTC, Morganamilo requested changes
I think this should be done a bit differently to fit with this tools philosophy of generating full reports will all information.

This is extra important in CI as you would have to fix + push + rerun loop to get all the information out of the tool to fix all mistakes.

Now that I'm back I can adjust the code myself if you prefer.

2024-06-25 12:30 UTC, Morganamilo commented on src/cli.rs
> +    pub max_allowed_bump: Option<BumpKind>,
I think maybe this should be `--max-bump` for brevity?

2024-06-25 12:30 UTC, Morganamilo commented on src/prdoc.rs
> +    if let Some(max_allowed_bump) = prdoc.max_allowed_bump {
I don't think this should be a seperate part. It should be a part of the end report that contains all the information.

I also think we should apply the limit on the actual semver change not the change the PRDoc claims.

2024-06-25 16:15 UTC, ggwpez commented
>Now that I'm back I can adjust the code myself if you prefer.

Yea please go ahead @Morganamilo.

2024-06-27 15:02 UTC, ggwpez commented
Output now looks like this:

![Screenshot 2024-06-27 at 17 02 05](https://github.com/paritytech/parity-publish/assets/10380170/af859b29-009b-4919-a33f-a956b7a548a0)

2024-06-27 15:15 UTC, Morganamilo commented on src/prdoc.rs
> +    if let Some(max_allowed_bump) = prdoc.max_allowed_bump {
Then maybe we output `max(predicted, prdoc)`

2024-06-27 16:19 UTC, ggwpez commented
<img width="650" alt="Screenshot 2024-06-27 at 18 19 42" src="https://github.com/paritytech/parity-publish/assets/10380170/e5947484-4af9-4c8f-8e66-6c74483c9291">

2024-06-28 09:26 UTC, Morganamilo approved these changes

2024-06-28 09:27 UTC, merged